// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"meul/inventory/internal/infrastructures"
)

// Injectors from wire.go:

// InitializeEvent creates an Event. It will error if the Event is staffed with
// a grumpy greeter.
func InitializeEvent(phrase string) (event.Event, error) {
	message := event.NewMessage()
	greeter := event.NewGreeter(message)
	eventEvent := event.NewEvent(greeter)
	return eventEvent, nil
}
