repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
        files: \.go$
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: go-critic
      - id: go-unit-tests
      - id: go-mod-tidy
