repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.4.0 # Use the latest stable version
  #   hooks:
  #     - id: trailing-whitespace
  #     - id: end-of-file-fixer
  #     - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy

  - repo: https://github.com/prettier/prettier
    rev: v3.0.0 # Use the latest stable version
    hooks:
      - id: prettier
        args: [--write]
