// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"meul/inventory/internal/infrastructures/drivers/postgres/migrations"
	"meul/inventory/internal/interfaces/migrations_resource_cli"
)

// Injectors from wire.go:

func InitializeMigrationHandler() (*migrations_resource_cli.MigrationCLI, error) {
	migrationConfig := _wireMigrationConfigValue
	migrationFilesOrderHandler := postgres_migrations.DefaultMigrationFilesOrderHandler()
	migrationFilesHandler := postgres_migrations.DefaultMigrationFilesHandler(migrationFilesOrderHandler)
	migrationHandler := postgres_migrations.DefaultMigrationHandler(migrationConfig, migrationFilesHandler)
	migrationCLI := migrations_resource_cli.DefaultMigrationCLI(migrationHandler)
	return migrationCLI, nil
}

var (
	_wireMigrationConfigValue = &migrations_resource_cli.MigrationConfig
)

// wire.go:

func ProvideMigrationHandler(config *postgres_migrations.MigrationConfig) postgres_migrations.MigrationHandler {

	return postgres_migrations.MigrationHandler{
		MigrationConfig: config,
	}
}

// WireSet is a set that includes all necessary providers
var WireSet = wire.NewSet(migrations_resource_cli.DefaultMigrationCLI, postgres_migrations.DefaultMigrationFilesOrderHandler, postgres_migrations.DefaultMigrationFilesHandler, postgres_migrations.DefaultMigrationHandler, wire.Value(&migrations_resource_cli.MigrationConfig), ProvideMigrationHandler)
